package com.aegis.identity.infrastructure.audit;

public enum AuditEventType {
    AUTH_LOGIN_SUCCESS,
    AUTH_LOGIN_FAILURE,
    AUTH_LOGOUT,
    AUTH_REFRESH_SUCCESS,
    AUTH_REFRESH_REUSE_DETECTED,
    OAUTH_LOGIN_SUCCESS,
    OAUTH_LINK_SUCCESS,
    OAUTH_LINK_FAILURE,
    ACCOUNT_CREATED,
    AUTHORIZATION_DENIED,
    TENANT_ACCESS_DENIED
}
