package com.aegis.identity.infrastructure.audit;

public enum AuditEventType {
  AUTH_LOGIN_SUCCESS,
  AUTH_LOGIN_FAILURE,
  AUTH_LOGOUT,
  AUTH_REFRESH_SUCCESS,
  AUTH_REFRESH_REUSE_DETECTED,
  OAUTH_LOGIN_SUCCESS,
  OAUTH_LINK_SUCCESS,
  OAUTH_LINK_FAILURE,
  ACCOUNT_CREATED,
  AUTHORIZATION_DENIED,
  TENANT_ACCESS_DENIED,

  // Identity Assurance Audit Events
  EMAIL_VERIFICATION_SENT,
  EMAIL_VERIFIED,
  EMAIL_VERIFICATION_FAILED,
  MFA_SETUP_STARTED,
  MFA_ENABLED,
  MFA_VERIFICATION_SUCCESS,
  MFA_VERIFICATION_FAILED,
  MFA_DISABLED,
  MFA_RECOVERY_USED,
  MFA_RECOVERY_CODES_REGENERATED,
  MFA_CHALLENGE_EXPIRED
}
